#! /bin/bash

cur=$(pwd)

sta=0

for git in $(find . -name .git); do
  dir="${git%.git}"
  cd "$dir"
  if [ -n "$(git status -s)" ]; then
    echo "$dir"
    git status -s
    sta=1
  fi
  cd "$cur"
done

exit $sta
