#! /bin/bash

cur=$(pwd)

if [ -n "$*" ]; then
  option="$*"
else
  option="status"
fi

for git in $(find . -name .git); do
  dir="${git%.git}"
  cd "$dir"
  echo "$dir"
  git $option
  echo
  cd "$cur"
done

echo "done."
