#! /bin/bash

cur=$(pwd)

if [ -n "$*" ]; then
  option="$*"
else
  option="status -s"
fi

for git in $(find $cur -name .git); do
  dir="${git%.git}"
  cd "$dir"
  echo "${dir#$cur/}"
  git $option
  echo
  cd "$cur"
done

echo "done."
