#! /bin/bash

echo sudo apt-get update
sudo apt-get update
echo sudo apt-get dist-upgrade -y
sudo apt-get dist-upgrade -y
echo sudo apt-get autoremove -y
sudo apt-get autoremove -y
echo sudo apt-get autoclean
sudo apt-get autoclean
echo Done.
